spring:
  datasource:
    url: jdbc:h2:~/person
    username: root
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    ddl-auto: create
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  file:
    name: ./person.log
    path: ./
  level:
    root: info